import  = [
  "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]

live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true

[font]
size = 8

[font.bold]
family = "Aesthetic Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Aesthetic Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Aesthetic Iosevka Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[shell]
program = "/usr/bin/zsh"

[scrolling]
history = 0
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
opacity = 0.7
decorations = "Full"
dynamic_padding = true
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 80

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
